Name: dropship-api
Host: 0.0.0.0
Port: 8888

MySQL:
  DataSource: "root:root123@tcp(127.0.0.1:3306)/dropship?charset=utf8mb4&parseTime=True&loc=Local"

Etcd:
  Hosts:
    - "127.0.0.1:2379"
  Key: "/dropship/config"

UserCenterRpc:
  Etcd:
    Hosts:
      - "127.0.0.1:2379"
    Key: user-center.rpc
