// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usercenter.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerifyTokenReq struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenReq) Reset()         { *m = VerifyTokenReq{} }
func (m *VerifyTokenReq) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenReq) ProtoMessage()    {}
func (*VerifyTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_babf089d71f2a8dc, []int{0}
}

func (m *VerifyTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenReq.Unmarshal(m, b)
}
func (m *VerifyTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenReq.Marshal(b, m, deterministic)
}
func (m *VerifyTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenReq.Merge(m, src)
}
func (m *VerifyTokenReq) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenReq.Size(m)
}
func (m *VerifyTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenReq proto.InternalMessageInfo

func (m *VerifyTokenReq) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type VerifyTokenResp struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Roles                []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyTokenResp) Reset()         { *m = VerifyTokenResp{} }
func (m *VerifyTokenResp) String() string { return proto.CompactTextString(m) }
func (*VerifyTokenResp) ProtoMessage()    {}
func (*VerifyTokenResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_babf089d71f2a8dc, []int{1}
}

func (m *VerifyTokenResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyTokenResp.Unmarshal(m, b)
}
func (m *VerifyTokenResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyTokenResp.Marshal(b, m, deterministic)
}
func (m *VerifyTokenResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyTokenResp.Merge(m, src)
}
func (m *VerifyTokenResp) XXX_Size() int {
	return xxx_messageInfo_VerifyTokenResp.Size(m)
}
func (m *VerifyTokenResp) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyTokenResp.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyTokenResp proto.InternalMessageInfo

func (m *VerifyTokenResp) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *VerifyTokenResp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *VerifyTokenResp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *VerifyTokenResp) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type CheckRoleReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role                 string   `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRoleReq) Reset()         { *m = CheckRoleReq{} }
func (m *CheckRoleReq) String() string { return proto.CompactTextString(m) }
func (*CheckRoleReq) ProtoMessage()    {}
func (*CheckRoleReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_babf089d71f2a8dc, []int{2}
}

func (m *CheckRoleReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRoleReq.Unmarshal(m, b)
}
func (m *CheckRoleReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRoleReq.Marshal(b, m, deterministic)
}
func (m *CheckRoleReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRoleReq.Merge(m, src)
}
func (m *CheckRoleReq) XXX_Size() int {
	return xxx_messageInfo_CheckRoleReq.Size(m)
}
func (m *CheckRoleReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRoleReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRoleReq proto.InternalMessageInfo

func (m *CheckRoleReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CheckRoleReq) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type CheckRoleResp struct {
	HasRole              bool     `protobuf:"varint,1,opt,name=has_role,json=hasRole,proto3" json:"has_role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRoleResp) Reset()         { *m = CheckRoleResp{} }
func (m *CheckRoleResp) String() string { return proto.CompactTextString(m) }
func (*CheckRoleResp) ProtoMessage()    {}
func (*CheckRoleResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_babf089d71f2a8dc, []int{3}
}

func (m *CheckRoleResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRoleResp.Unmarshal(m, b)
}
func (m *CheckRoleResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRoleResp.Marshal(b, m, deterministic)
}
func (m *CheckRoleResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRoleResp.Merge(m, src)
}
func (m *CheckRoleResp) XXX_Size() int {
	return xxx_messageInfo_CheckRoleResp.Size(m)
}
func (m *CheckRoleResp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRoleResp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRoleResp proto.InternalMessageInfo

func (m *CheckRoleResp) GetHasRole() bool {
	if m != nil {
		return m.HasRole
	}
	return false
}

type GetUserInfoReq struct {
	UserId               int64    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_babf089d71f2a8dc, []int{4}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserInfo struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string   `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Status               string   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Roles                []string `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_babf089d71f2a8dc, []int{5}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UserInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func init() {
	proto.RegisterType((*VerifyTokenReq)(nil), "usercenter.VerifyTokenReq")
	proto.RegisterType((*VerifyTokenResp)(nil), "usercenter.VerifyTokenResp")
	proto.RegisterType((*CheckRoleReq)(nil), "usercenter.CheckRoleReq")
	proto.RegisterType((*CheckRoleResp)(nil), "usercenter.CheckRoleResp")
	proto.RegisterType((*GetUserInfoReq)(nil), "usercenter.GetUserInfoReq")
	proto.RegisterType((*UserInfo)(nil), "usercenter.UserInfo")
}

func init() {
	proto.RegisterFile("usercenter.proto", fileDescriptor_babf089d71f2a8dc)
}

var fileDescriptor_babf089d71f2a8dc = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0x4d, 0xa1, 0x14, 0x18, 0x14, 0xcd, 0x84, 0xe8, 0x52, 0x2f, 0xa4, 0x07, 0xa3, 0x1e, 0x30,
	0xd1, 0xa3, 0x07, 0x8d, 0x24, 0x1a, 0xaf, 0x8d, 0x7a, 0xf0, 0x42, 0x16, 0x18, 0x42, 0x05, 0xda,
	0xda, 0x5d, 0x4c, 0xfc, 0x0b, 0xfe, 0x41, 0xff, 0x8e, 0x99, 0x2d, 0x1f, 0xdb, 0x43, 0x4d, 0xbc,
	0xed, 0x9b, 0xf7, 0xe6, 0xa3, 0xef, 0x15, 0x0e, 0x57, 0x8a, 0xb2, 0x31, 0xc5, 0x9a, 0xb2, 0x7e,
	0x9a, 0x25, 0x3a, 0x41, 0xd8, 0x55, 0x82, 0x53, 0x68, 0xbf, 0x52, 0x16, 0x4d, 0xbf, 0x9e, 0x93,
	0x39, 0xc5, 0x21, 0x7d, 0x60, 0x07, 0x6a, 0x9a, 0xdf, 0xc2, 0xe9, 0x39, 0x67, 0xcd, 0x30, 0x07,
	0xc1, 0x3b, 0x1c, 0x14, 0x74, 0x2a, 0xc5, 0x63, 0xa8, 0xf3, 0xa0, 0x61, 0x34, 0x31, 0xd2, 0x6a,
	0xe8, 0x31, 0x7c, 0x9a, 0xf0, 0x04, 0x5a, 0xca, 0x68, 0x21, 0x2a, 0xf9, 0x04, 0x03, 0x10, 0xc1,
	0x8d, 0xe5, 0x92, 0x44, 0xd5, 0x14, 0xcd, 0x9b, 0x95, 0x59, 0xb2, 0x20, 0x25, 0xdc, 0x5e, 0x95,
	0x95, 0x06, 0x04, 0x37, 0xb0, 0x37, 0x98, 0xd1, 0x78, 0x1e, 0x26, 0x0b, 0xe2, 0x8b, 0x4a, 0x17,
	0x21, 0xb8, 0xdc, 0xb1, 0xde, 0x63, 0xde, 0xc1, 0x05, 0xec, 0x5b, 0xcd, 0x2a, 0xc5, 0x2e, 0x34,
	0x66, 0x52, 0x0d, 0x8d, 0x90, 0xdb, 0x1b, 0x61, 0x7d, 0x26, 0x15, 0xd3, 0xc1, 0x39, 0xb4, 0x1f,
	0x49, 0xbf, 0xf0, 0xb0, 0x78, 0x9a, 0xfc, 0xb5, 0x2a, 0xf8, 0x76, 0xa0, 0xb1, 0x11, 0x62, 0x1b,
	0x2a, 0x5b, 0x41, 0x25, 0xfa, 0xcf, 0x07, 0x1f, 0x81, 0x27, 0x3f, 0xa5, 0x96, 0x99, 0x70, 0x4d,
	0x75, 0x8d, 0xb8, 0xae, 0xb4, 0xd4, 0x2b, 0x25, 0x6a, 0x79, 0x3d, 0x47, 0x3b, 0x83, 0x3c, 0xcb,
	0xa0, 0xab, 0x1f, 0x07, 0x80, 0x8f, 0x19, 0x98, 0x0c, 0xf1, 0x01, 0x5a, 0x56, 0x36, 0xe8, 0xf7,
	0xad, 0xc4, 0x8b, 0xe1, 0xfa, 0x27, 0xa5, 0x9c, 0x4a, 0xf1, 0x0e, 0x9a, 0x5b, 0xeb, 0x50, 0xd8,
	0x4a, 0x3b, 0x0e, 0xbf, 0x5b, 0xc2, 0xa8, 0x14, 0x6f, 0xa1, 0x65, 0x19, 0x5a, 0xbc, 0xa4, 0xe8,
	0xb4, 0xdf, 0xb1, 0xb9, 0x0d, 0x71, 0xef, 0xbd, 0xb9, 0xfd, 0xcb, 0x74, 0x34, 0xf2, 0xcc, 0x9f,
	0x7a, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xbe, 0x5d, 0x33, 0xbd, 0x02, 0x00, 0x00,
}
